	
SELECT * FROM customer LIMIT 5;

--Question 1. What is the total revenue generated by male versus female customer?
SELECT Gender, SUM (purchase_amount) AS revenue
FROM customer
GROUP BY gender

--Question 2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id , purchase_amount 
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--Question 3. Which are the top five products with the highest average review rating? 
SELECT item_purchased, AVG(review_rating) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER 

--Question 4. Compare the average purchase amount between standard and express shipping 
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type

--Question 5. Do subscribe customers spend more? compare average spend and total revenue between subscribers and non subscribers.
SELECT subscriPtion_status

--Question 6. Which five products have the highest percentage of purchases with discounts applied? 
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

--Question 7. Segment customers into new, returning,  and loyal based on their total number of previous purchases, and show the amount of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	ELSE 'LOYAL'
	END AS customer_segment
FROM customer	
)

SELECT customer_segment, COUNT(*) AS "NUMBER OF CUSTOMER"
FROM customer_type
GROUP BY customer_segment



--Question 8. What are the top 3 most purchased products we didn't each category?
WITH item_counts AS (
SELECT catEgory,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT (customer_id)DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Question 9. Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Question 10. What is the revenue contribution of each age group?
SELECT age_groups,
SUM (purchase_amount) AS total_revenue
FROM customer
GROUP BY age_groups
ORDER BY total_revenue DESC;
